id: I732F4B53
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:36:05.215368'
last_modified: '2022-06-18T22:36:05.215382'
parser: null
source_metadata:
  title: Gong dkar Phrin las rnam rgyals Record of Teachings Received
  author: gong dkar phrin las rnam rgyal/
  description: 'Digital version 3.0 {Wylie}; WYLIE COPY of master xml (completed:
    2017-10-27); converted from external file, revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - 'Digital edition:Sakya Research Centre; This text was initially inputted by Saṃ
    bho ṃa''i dbon brgyud dpe tshogs (Digital Text version/id: 1.doc, 2.doc, 3.doc).
    (src)'
  - Text input:saM bho Ta'i dbon brgyud dpe tshogs/
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/444
  bases:
    48be:
      title: Gong dkar Phrin las rnam rgyals Record of Teachings Received
      order: 1
      base_file: 48be.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
